name: Build and Release SimpleSimulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            runtime: win-x64
            output_file: SimpleSimulator.exe
          - os: ubuntu-latest
            runtime: linux-x64
            output_file: SimpleSimulator.AppImage

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore src/SimpleSimulator.csproj

      - name: Build Project
        run: dotnet build src/SimpleSimulator.csproj --configuration Release --no-restore

      - name: Publish Executable
        run: dotnet publish src/SimpleSimulator.csproj -c Release -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true -o ./publish

      - name: Rename Output Files (Windows)
        if: matrix.os == 'windows-latest'
        run: mv ./publish/SimpleSimulator.exe ./publish/${{ matrix.output_file }}

      - name: Rename Output Files (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          chmod +x ./publish/SimpleSimulator
          mv ./publish/SimpleSimulator ./publish/${{ matrix.output_file }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleSimulator-${{ matrix.runtime }}
          path: ./publish/${{ matrix.output_file }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: SimpleSimulator-win-x64
          path: ./release

      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: SimpleSimulator-linux-x64
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./release/SimpleSimulator.exe
            ./release/SimpleSimulator.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}
