name: Build and Release SimpleSimulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            runtime: win-x64
            output: SimpleSimulator.exe
          - os: ubuntu-latest
            runtime: linux-x64
            output: SimpleSimulator.AppImage

    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Package Linux Binary (AppImage)
        if: matrix.os == 'ubuntu-latest'
        run: |
          chmod +x ./publish/SimpleSimulator
          mv ./publish/SimpleSimulator ./publish/SimpleSimulator.AppImage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleSimulator-${{ matrix.runtime }}
          path: ./publish/*
  
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: SimpleSimulator-win-x64
          path: ./release/windows

      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: SimpleSimulator-linux-x64
          path: ./release/linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./release/windows/SimpleSimulator.exe
            ./release/linux/SimpleSimulator.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}
